language: php
dist: trusty

php:
  - 7.0
  - 7.1
  - 7.2

before_script:
  - "composer self-update"
  - "composer --version"
  - "composer install --no-interaction"

script:
  - "./vendor/bin/phpunit -c phpunit.xml.dist  --coverage-clover=clover.xml"

after_script:
  - "php vendor/bin/codacycoverage clover clover.xml"
